// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/shorten-url.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.57.4";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var shorten_url_default = defineTool({
  name: "shorten_url",
  title: "Shorten URL",
  description: "Create a shortened URL (with QR code) for the signed-in user. Optionally provide a custom short code.",
  inputSchema: {
    originalUrl: z.string().url().describe("The long URL to shorten."),
    customCode: z.string().trim().min(1).max(20).regex(/^[a-z0-9-]+$/i).optional().describe("Optional custom short code (letters, numbers, hyphens).")
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async ({ originalUrl, customCode }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    let shortCode = customCode;
    if (!shortCode) {
      for (let i = 0; i < 10 && !shortCode; i++) {
        const { data, error } = await supabase.rpc("generate_short_code");
        if (error) {
          return {
            content: [{ type: "text", text: error.message }],
            isError: true
          };
        }
        const { data: existing } = await supabase.from("urls").select("id").eq("short_code", data).maybeSingle();
        if (!existing) shortCode = data;
      }
    }
    if (!shortCode) {
      return {
        content: [{ type: "text", text: "Failed to generate unique short code" }],
        isError: true
      };
    }
    const baseUrl = "https://lnkzip.com";
    const shortUrl = `${baseUrl}/${shortCode}`;
    const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(shortUrl)}`;
    const { data: row, error: insertError } = await supabase.from("urls").insert({
      user_id: userId,
      original_url: originalUrl,
      short_code: shortCode,
      short_url: shortUrl,
      qr_code_url: qrCodeUrl,
      title: originalUrl
    }).select().single();
    if (insertError) {
      return {
        content: [{ type: "text", text: insertError.message }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Shortened: ${shortUrl}
QR: ${qrCodeUrl}`
        }
      ],
      structuredContent: {
        id: row.id,
        shortCode,
        shortUrl,
        qrCodeUrl,
        originalUrl
      }
    };
  }
});

// src/lib/mcp/tools/list-urls.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.57.4";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_urls_default = defineTool2({
  name: "list_urls",
  title: "List my shortened URLs",
  description: "List the signed-in user's shortened URLs with click counts, newest first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum number of URLs to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("urls").select("id, short_code, short_url, original_url, title, click_count, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { urls: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zyrtsgwvpxewgfpqxfmn";
var mcp_default = defineMcp({
  name: "lnkzip-mcp",
  title: "lnkzip MCP",
  version: "0.1.0",
  instructions: "Tools for lnkzip URL shortener. Use `shorten_url` to create a new short link (with QR code) and `list_urls` to fetch the signed-in user's links with click counts.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [shorten_url_default, list_urls_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
