// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyrtsgwvpxewgfpqxfmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5cnRzZ3d2cHhld2dmcHF4Zm1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDU3NTUsImV4cCI6MjA3MzEyMTc1NX0.QrWMI94K2lgHnOlGrQ9DmpYjcQBuaa9YcBU-p5QOQvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});