name: Keep Supabase Alive
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API Gateway
        run: curl -i https://supabase.co
